name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write

jobs:
  lint:
    name: Lint y verificar sintaxis
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.9.0'
        cache: 'npm'

    - name: Instalar dependencias
      run: npm install

    - name: Convertir saltos de línea a LF en todos los JS
      run: |
        echo "Convirtiendo saltos de línea a LF..."
        find . -type f -name "*.js" -not -path "./node_modules/*" -not -path "./dist/*" -exec dos2unix {} \;

    - name: Ejecutar ESLint con fix
      run: npm run lint:fix

    - name: Verificar sintaxis JS
      run: |
        echo "Verificando sintaxis..."
        find . -name "*.js" -not -path "./node_modules/*" -not -path "./dist/*" -exec node -c {} \;

    - name: Ejecutar ESLint
      run: npm run lint

    - name: Verificar formato JSON
      run: |
        find . -name "*.json" -not -path "./node_modules/*" -not -path "./dist/*" -exec node -e "JSON.parse(require('fs').readFileSync('{}', 'utf8'))" \;

    - name: Verificar estructura del proyecto
      run: |
        test -f "package.json" || exit 1
        test -f "main.js" || exit 1
        test -f "index.html" || exit 1
        test -d "js" || exit 1
        test -d "js/families" || exit 1
        test -d "js/utils" || exit 1
        echo "✅ Estructura correcta"

  build-linux:
    name: Build en Linux
    runs-on: ubuntu-latest
    needs: lint
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '22.9.0'
        cache: 'npm'

    - run: npm ci

    - run: timeout 10s npm start || true

    - run: npm run dist

    - run: ls -la dist/

    - uses: actions/upload-artifact@v4
      with:
        name: electron-app-linux
        path: dist/
        retention-days: 7

  build-windows:
    name: Build en Windows
    runs-on: windows-latest
    needs: lint
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '22.9.0'
        cache: 'npm'

    - run: npm ci

    - run: timeout 10s npm start || true

    - run: npm run dist

    - run: dir dist\

    - uses: actions/upload-artifact@v4
      with:
        name: electron-app-windows
        path: dist/
        retention-days: 7

  build-macos:
    name: Build en macOS
    runs-on: macos-latest
    needs: lint
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '22.9.0'
        cache: 'npm'

    - run: npm ci

    - run: timeout 10s npm start || true

    - run: npm run dist

    - run: ls -la dist/

    - uses: actions/upload-artifact@v4
      with:
        name: electron-app-macos
        path: dist/
        retention-days: 7

  test:
    name: Ejecutar tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '22.9.0'
        cache: 'npm'

    - run: npm ci

    - run: |
        echo "Verificando archivos principales..."
        node -c main.js
        node -c server.js
        find js/ -name "*.js" -exec node -c {} \;
        echo "✅ Archivos OK"

  release:
    name: Crear Release
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows, build-macos]
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.9.0'

    - name: Instalar dependencias
      run: npm ci

    - name: Leer versión desde package.json
      id: version
      run: echo "version=$(node -p \"require('./package.json').version\")" >> $GITHUB_OUTPUT

    - name: Crear ZIP del proyecto completo
      run: |
        mkdir -p artifacts
        zip -r artifacts/project-source-v${{ steps.version.outputs.version }}.zip . \
          -x "node_modules/**" ".git/**" "dist/**" "artifacts/**" ".github/**" "*.zip"

    - name: Descargar artefactos de build
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Crear Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.version.outputs.version }}
        name: Release v${{ steps.version.outputs.version }}
        files: |
          artifacts/electron-app-linux/**/*
          artifacts/electron-app-windows/**/*
          artifacts/electron-app-macos/**/*
          artifacts/project-source-v${{ steps.version.outputs.version }}.zip
        body: |
          ## Generador de Tests Playwright
          
          ### Cambios en esta versión:
          - Build automático para Linux, Windows y macOS
          - Verificación de sintaxis, estructura y pruebas básicas
          
          ### Archivos incluidos:
          - Aplicaciones Electron por plataforma
          - Código fuente completo (comprimido)
          - Documentación, configuración y recursos

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
